#!/usr/bin/env bash
# vim: ft=bash

set -e

source "$(find . -name .shared.sh)"

export BAZEL_HOME="${BAZEL_HOME:-"${HOME}/bazel"}"
export PATH="${BAZEL_HOME}/bin:${PATH}"

function setup() {
  puts "Downloading Bazelisk..."
  curl -sLO "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64"

  puts "Setting up local bazel installation in" "${BAZEL_HOME}"
  mkdir -p "${BAZEL_HOME}/bin/"
  mv bazelisk-linux-amd64 "${BAZEL_HOME}/bin/bazel"
  chmod +x "${BAZEL_HOME}/bin/bazel"

  # make bazel available globally
  [[ -f /usr/local/bin/bazel ]] || ln -s "${BAZEL_HOME}/bin/bazel" /usr/local/bin/bazel

  puts "All done ${bldgrn}✔"
}

function main() {
  setup "$@"
}

main "$@"
